# Generated by Django 5.2.6 on 2025-10-02 06:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadedFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=255)),
                ('filetype', models.CharField(max_length=50)),
                ('filesize', models.PositiveBigIntegerField()),
                ('file', models.FileField(upload_to='documents/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_files', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LoanDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_number', models.IntegerField(default=0)),
                ('document_type', models.CharField(blank=True, max_length=255, null=True)),
                ('property_address', models.TextField(blank=True, null=True)),
                ('tax_year', models.CharField(blank=True, max_length=10, null=True)),
                ('census_tract', models.CharField(blank=True, max_length=50, null=True)),
                ('property_rights_appraised', models.CharField(blank=True, max_length=50, null=True)),
                ('neighborhood_name', models.TextField(blank=True, null=True)),
                ('assignment_type', models.CharField(blank=True, max_length=255, null=True)),
                ('currently_offered_for_sale', models.CharField(blank=True, max_length=10, null=True)),
                ('data_source', models.CharField(blank=True, max_length=255, null=True)),
                ('list_date', models.CharField(blank=True, max_length=50, null=True)),
                ('seller_is_owner_of_record', models.CharField(blank=True, max_length=10, null=True)),
                ('financial_assistance', models.CharField(blank=True, max_length=10, null=True)),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('property_values', models.CharField(blank=True, max_length=255, null=True)),
                ('built_up', models.CharField(blank=True, max_length=50, null=True)),
                ('demand_supply', models.CharField(blank=True, max_length=50, null=True)),
                ('growth', models.CharField(blank=True, max_length=50, null=True)),
                ('marketing_time', models.CharField(blank=True, max_length=255, null=True)),
                ('price_range_one_unit', models.CharField(blank=True, max_length=255, null=True)),
                ('dimensions', models.CharField(blank=True, max_length=100, null=True)),
                ('area', models.CharField(blank=True, max_length=50, null=True)),
                ('shape', models.CharField(blank=True, max_length=50, null=True)),
                ('view', models.CharField(blank=True, max_length=50, null=True)),
                ('zoning_compliance', models.CharField(blank=True, max_length=255, null=True)),
                ('utilities', models.CharField(blank=True, max_length=255, null=True)),
                ('loan_amount', models.CharField(blank=True, max_length=50, null=True)),
                ('interest_rate', models.CharField(blank=True, max_length=50, null=True)),
                ('product', models.CharField(blank=True, max_length=255, null=True)),
                ('purpose', models.CharField(blank=True, max_length=50, null=True)),
                ('loan_term', models.CharField(blank=True, max_length=50, null=True)),
                ('borrower', models.CharField(blank=True, max_length=255, null=True)),
                ('origination_charges', models.CharField(blank=True, max_length=50, null=True)),
                ('services_borrower_did_shop_for', models.CharField(blank=True, max_length=255, null=True)),
                ('initial_escrow_payment_at_closing', models.CharField(blank=True, max_length=50, null=True)),
                ('total_other_costs', models.CharField(blank=True, max_length=50, null=True)),
                ('total_payoffs_and_payments', models.CharField(blank=True, max_length=50, null=True)),
                ('initial_escrow_payment', models.CharField(blank=True, max_length=50, null=True)),
                ('origination_fee', models.CharField(blank=True, max_length=50, null=True)),
                ('title_fee', models.CharField(blank=True, max_length=50, null=True)),
                ('recording_fee', models.CharField(blank=True, max_length=50, null=True)),
                ('total_fees', models.CharField(blank=True, max_length=50, null=True)),
                ('borrower_name', models.CharField(blank=True, max_length=255, null=True)),
                ('property_field', models.TextField(blank=True, null=True)),
                ('sale_price', models.CharField(blank=True, max_length=50, null=True)),
                ('loan_type', models.CharField(blank=True, max_length=50, null=True)),
                ('rate_lock', models.CharField(blank=True, max_length=50, null=True)),
                ('estimated_closing_costs', models.CharField(blank=True, max_length=50, null=True)),
                ('services_you_cannot_shop_for', models.CharField(blank=True, max_length=255, null=True)),
                ('services_you_can_shop_for', models.CharField(blank=True, max_length=255, null=True)),
                ('total_closing_costs', models.CharField(blank=True, max_length=50, null=True)),
                ('estimated_cash_to_close', models.CharField(blank=True, max_length=50, null=True)),
                ('lender_name', models.CharField(blank=True, max_length=255, null=True)),
                ('loan_officer_name', models.CharField(blank=True, max_length=255, null=True)),
                ('loan_officer_email', models.CharField(blank=True, max_length=255, null=True)),
                ('loan_officer_phone', models.CharField(blank=True, max_length=50, null=True)),
                ('date_issued', models.CharField(blank=True, max_length=50, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('uploaded_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loan_documents', to='docextraction.uploadedfile')),
            ],
        ),
    ]
