# Generated by Django 5.2.6 on 2025-09-24 04:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docextraction', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExtractedField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loan_amount', models.CharField(blank=True, max_length=255, null=True)),
                ('date_issued', models.CharField(blank=True, max_length=50, null=True)),
                ('borrower_name', models.CharField(blank=True, max_length=255, null=True)),
                ('lender_name', models.CharField(blank=True, max_length=255, null=True)),
                ('loan_term', models.CharField(blank=True, max_length=50, null=True)),
                ('interest_rate', models.CharField(blank=True, max_length=50, null=True)),
                ('apr', models.CharField(blank=True, max_length=50, null=True)),
                ('closing_date', models.CharField(blank=True, max_length=50, null=True)),
                ('disbursement_date', models.CharField(blank=True, max_length=50, null=True)),
                ('sales_price', models.CharField(blank=True, max_length=50, null=True)),
                ('document_type', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('document', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='extracted_data', to='docextraction.docfile')),
            ],
        ),
    ]
