-- public.auth_group definition

-- Drop table

-- DROP TABLE public.auth_group;

CREATE TABLE public.auth_group (
	id int4 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START 1 CACHE 1 NO CYCLE) NOT NULL,
	"name" varchar(150) NOT NULL,
	CONSTRAINT auth_group_name_key UNIQUE (name),
	CONSTRAINT auth_group_pkey PRIMARY KEY (id)
);
CREATE INDEX auth_group_name_a6ea08ec_like ON public.auth_group USING btree (name varchar_pattern_ops);


-- public.auth_user definition

-- Drop table

-- DROP TABLE public.auth_user;

CREATE TABLE public.auth_user (
	id int4 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START 1 CACHE 1 NO CYCLE) NOT NULL,
	"password" varchar(128) NOT NULL,
	last_login timestamptz NULL,
	is_superuser bool NOT NULL,
	username varchar(150) NOT NULL,
	first_name varchar(150) NOT NULL,
	last_name varchar(150) NOT NULL,
	email varchar(254) NOT NULL,
	is_staff bool NOT NULL,
	is_active bool NOT NULL,
	date_joined timestamptz NOT NULL,
	CONSTRAINT auth_user_pkey PRIMARY KEY (id),
	CONSTRAINT auth_user_username_key UNIQUE (username)
);
CREATE INDEX auth_user_username_6821ab7c_like ON public.auth_user USING btree (username varchar_pattern_ops);


-- public.django_content_type definition

-- Drop table

-- DROP TABLE public.django_content_type;

CREATE TABLE public.django_content_type (
	id int4 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START 1 CACHE 1 NO CYCLE) NOT NULL,
	app_label varchar(100) NOT NULL,
	model varchar(100) NOT NULL,
	CONSTRAINT django_content_type_app_label_model_76bd3d3b_uniq UNIQUE (app_label, model),
	CONSTRAINT django_content_type_pkey PRIMARY KEY (id)
);


-- public.django_migrations definition

-- Drop table

-- DROP TABLE public.django_migrations;

CREATE TABLE public.django_migrations (
	id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
	app varchar(255) NOT NULL,
	"name" varchar(255) NOT NULL,
	applied timestamptz NOT NULL,
	CONSTRAINT django_migrations_pkey PRIMARY KEY (id)
);


-- public.django_session definition

-- Drop table

-- DROP TABLE public.django_session;

CREATE TABLE public.django_session (
	session_key varchar(40) NOT NULL,
	session_data text NOT NULL,
	expire_date timestamptz NOT NULL,
	CONSTRAINT django_session_pkey PRIMARY KEY (session_key)
);
CREATE INDEX django_session_expire_date_a5c62663 ON public.django_session USING btree (expire_date);
CREATE INDEX django_session_session_key_c0390e0f_like ON public.django_session USING btree (session_key varchar_pattern_ops);


-- public.accounts_emailotp definition

-- Drop table

-- DROP TABLE public.accounts_emailotp;

CREATE TABLE public.accounts_emailotp (
	id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
	otp varchar(10) NOT NULL,
	purpose varchar(20) NOT NULL,
	created_at timestamptz NOT NULL,
	used bool NOT NULL,
	expires_at timestamptz NOT NULL,
	user_id int4 NOT NULL,
	CONSTRAINT accounts_emailotp_pkey PRIMARY KEY (id),
	CONSTRAINT accounts_emailotp_user_id_137ae83b_fk_auth_user_id FOREIGN KEY (user_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED
);
CREATE INDEX accounts_emailotp_user_id_137ae83b ON public.accounts_emailotp USING btree (user_id);


-- public.accounts_passwordresetotp definition

-- Drop table

-- DROP TABLE public.accounts_passwordresetotp;

CREATE TABLE public.accounts_passwordresetotp (
	id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
	otp varchar(6) NOT NULL,
	created_at timestamptz NOT NULL,
	user_id int4 NOT NULL,
	CONSTRAINT accounts_passwordresetotp_pkey PRIMARY KEY (id),
	CONSTRAINT accounts_passwordresetotp_user_id_b1de1bbc_fk_auth_user_id FOREIGN KEY (user_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED
);
CREATE INDEX accounts_passwordresetotp_user_id_b1de1bbc ON public.accounts_passwordresetotp USING btree (user_id);


-- public.auth_permission definition

-- Drop table

-- DROP TABLE public.auth_permission;

CREATE TABLE public.auth_permission (
	id int4 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START 1 CACHE 1 NO CYCLE) NOT NULL,
	"name" varchar(255) NOT NULL,
	content_type_id int4 NOT NULL,
	codename varchar(100) NOT NULL,
	CONSTRAINT auth_permission_content_type_id_codename_01ab375a_uniq UNIQUE (content_type_id, codename),
	CONSTRAINT auth_permission_pkey PRIMARY KEY (id),
	CONSTRAINT auth_permission_content_type_id_2f476e4b_fk_django_co FOREIGN KEY (content_type_id) REFERENCES public.django_content_type(id) DEFERRABLE INITIALLY DEFERRED
);
CREATE INDEX auth_permission_content_type_id_2f476e4b ON public.auth_permission USING btree (content_type_id);


-- public.auth_user_groups definition

-- Drop table

-- DROP TABLE public.auth_user_groups;

CREATE TABLE public.auth_user_groups (
	id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
	user_id int4 NOT NULL,
	group_id int4 NOT NULL,
	CONSTRAINT auth_user_groups_pkey PRIMARY KEY (id),
	CONSTRAINT auth_user_groups_user_id_group_id_94350c0c_uniq UNIQUE (user_id, group_id),
	CONSTRAINT auth_user_groups_group_id_97559544_fk_auth_group_id FOREIGN KEY (group_id) REFERENCES public.auth_group(id) DEFERRABLE INITIALLY DEFERRED,
	CONSTRAINT auth_user_groups_user_id_6a12ed8b_fk_auth_user_id FOREIGN KEY (user_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED
);
CREATE INDEX auth_user_groups_group_id_97559544 ON public.auth_user_groups USING btree (group_id);
CREATE INDEX auth_user_groups_user_id_6a12ed8b ON public.auth_user_groups USING btree (user_id);


-- public.auth_user_user_permissions definition

-- Drop table

-- DROP TABLE public.auth_user_user_permissions;

CREATE TABLE public.auth_user_user_permissions (
	id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
	user_id int4 NOT NULL,
	permission_id int4 NOT NULL,
	CONSTRAINT auth_user_user_permissions_pkey PRIMARY KEY (id),
	CONSTRAINT auth_user_user_permissions_user_id_permission_id_14a6b632_uniq UNIQUE (user_id, permission_id),
	CONSTRAINT auth_user_user_permi_permission_id_1fbb5f2c_fk_auth_perm FOREIGN KEY (permission_id) REFERENCES public.auth_permission(id) DEFERRABLE INITIALLY DEFERRED,
	CONSTRAINT auth_user_user_permissions_user_id_a95ead1b_fk_auth_user_id FOREIGN KEY (user_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED
);
CREATE INDEX auth_user_user_permissions_permission_id_1fbb5f2c ON public.auth_user_user_permissions USING btree (permission_id);
CREATE INDEX auth_user_user_permissions_user_id_a95ead1b ON public.auth_user_user_permissions USING btree (user_id);


-- public.django_admin_log definition

-- Drop table

-- DROP TABLE public.django_admin_log;

CREATE TABLE public.django_admin_log (
	id int4 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START 1 CACHE 1 NO CYCLE) NOT NULL,
	action_time timestamptz NOT NULL,
	object_id text NULL,
	object_repr varchar(200) NOT NULL,
	action_flag int2 NOT NULL,
	change_message text NOT NULL,
	content_type_id int4 NULL,
	user_id int4 NOT NULL,
	CONSTRAINT django_admin_log_action_flag_check CHECK ((action_flag >= 0)),
	CONSTRAINT django_admin_log_pkey PRIMARY KEY (id),
	CONSTRAINT django_admin_log_content_type_id_c4bce8eb_fk_django_co FOREIGN KEY (content_type_id) REFERENCES public.django_content_type(id) DEFERRABLE INITIALLY DEFERRED,
	CONSTRAINT django_admin_log_user_id_c564eba6_fk_auth_user_id FOREIGN KEY (user_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED
);
CREATE INDEX django_admin_log_content_type_id_c4bce8eb ON public.django_admin_log USING btree (content_type_id);
CREATE INDEX django_admin_log_user_id_c564eba6 ON public.django_admin_log USING btree (user_id);


-- public.docextraction_uploadedfile definition

-- Drop table

-- DROP TABLE public.docextraction_uploadedfile;

CREATE TABLE public.docextraction_uploadedfile (
	id serial4 NOT NULL,
	user_id int4 NOT NULL,
	filename varchar(255) NOT NULL,
	filetype varchar(50) NOT NULL,
	filesize int8 NOT NULL,
	file varchar(255) NOT NULL,
	uploaded_at timestamptz DEFAULT CURRENT_TIMESTAMP NULL,
	CONSTRAINT docextraction_uploadedfile_pkey PRIMARY KEY (id),
	CONSTRAINT docextraction_uploadedfile_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.auth_user(id) ON DELETE CASCADE
);


-- public.auth_group_permissions definition

-- Drop table

-- DROP TABLE public.auth_group_permissions;

CREATE TABLE public.auth_group_permissions (
	id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
	group_id int4 NOT NULL,
	permission_id int4 NOT NULL,
	CONSTRAINT auth_group_permissions_group_id_permission_id_0cd325b0_uniq UNIQUE (group_id, permission_id),
	CONSTRAINT auth_group_permissions_pkey PRIMARY KEY (id),
	CONSTRAINT auth_group_permissio_permission_id_84c5c92e_fk_auth_perm FOREIGN KEY (permission_id) REFERENCES public.auth_permission(id) DEFERRABLE INITIALLY DEFERRED,
	CONSTRAINT auth_group_permissions_group_id_b120cbf9_fk_auth_group_id FOREIGN KEY (group_id) REFERENCES public.auth_group(id) DEFERRABLE INITIALLY DEFERRED
);
CREATE INDEX auth_group_permissions_group_id_b120cbf9 ON public.auth_group_permissions USING btree (group_id);
CREATE INDEX auth_group_permissions_permission_id_84c5c92e ON public.auth_group_permissions USING btree (permission_id);


-- public.docextraction_loandocument definition

-- Drop table

-- DROP TABLE public.docextraction_loandocument;

CREATE TABLE public.docextraction_loandocument (
	id serial4 NOT NULL,
	uploaded_file_id int4 NOT NULL,
	user_id int4 NOT NULL,
	page_number int4 DEFAULT 0 NULL,
	document_type varchar(255) NULL,
	property_address text NULL,
	tax_year varchar(10) NULL,
	census_tract varchar(50) NULL,
	property_rights_appraised varchar(50) NULL,
	neighborhood_name text NULL,
	assignment_type varchar(255) NULL,
	currently_offered_for_sale varchar(10) NULL,
	data_source varchar(255) NULL,
	list_date varchar(50) NULL,
	seller_is_owner_of_record varchar(10) NULL,
	financial_assistance varchar(10) NULL,
	"location" varchar(255) NULL,
	property_values varchar(255) NULL,
	built_up varchar(50) NULL,
	demand_supply varchar(50) NULL,
	growth varchar(50) NULL,
	marketing_time varchar(255) NULL,
	price_range_one_unit varchar(255) NULL,
	dimensions varchar(100) NULL,
	area varchar(50) NULL,
	shape varchar(50) NULL,
	"view" varchar(50) NULL,
	zoning_compliance varchar(255) NULL,
	utilities varchar(255) NULL,
	loan_amount varchar(50) NULL,
	interest_rate varchar(50) NULL,
	product varchar(255) NULL,
	purpose varchar(50) NULL,
	loan_term varchar(50) NULL,
	borrower varchar(255) NULL,
	origination_charges varchar(50) NULL,
	services_borrower_did_shop_for varchar(255) NULL,
	initial_escrow_payment_at_closing varchar(50) NULL,
	total_other_costs varchar(50) NULL,
	total_payoffs_and_payments varchar(50) NULL,
	initial_escrow_payment varchar(50) NULL,
	origination_fee varchar(50) NULL,
	title_fee varchar(50) NULL,
	recording_fee varchar(50) NULL,
	total_fees varchar(50) NULL,
	borrower_name varchar(255) NULL,
	property_field text NULL,
	sale_price varchar(50) NULL,
	loan_type varchar(50) NULL,
	rate_lock varchar(50) NULL,
	estimated_closing_costs varchar(50) NULL,
	services_you_cannot_shop_for varchar(255) NULL,
	services_you_can_shop_for varchar(255) NULL,
	total_closing_costs varchar(50) NULL,
	estimated_cash_to_close varchar(50) NULL,
	lender_name varchar(255) NULL,
	loan_officer_name varchar(255) NULL,
	loan_officer_email varchar(255) NULL,
	loan_officer_phone varchar(50) NULL,
	date_issued varchar(50) NULL,
	CONSTRAINT docextraction_loandocument_pkey PRIMARY KEY (id),
	CONSTRAINT docextraction_loandocument_uploaded_file_id_fkey FOREIGN KEY (uploaded_file_id) REFERENCES public.docextraction_uploadedfile(id) ON DELETE CASCADE,
	CONSTRAINT docextraction_loandocument_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.auth_user(id) ON DELETE CASCADE
);